server:
  port: 8012

spring:
  profiles:
    active: dev
  application:
    name: mall-job-application
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mariadb://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/my_mall?characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}

  mail:
    protocol: ${MAIL_PROTOCOL:smtp}
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    default-encoding: ${MAIL_DEFAULT_ENCODING:UTF-8}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true

my-mall:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400}   # 1 天(秒)

  captcha:
    expiration: 60

  quartz:
    core-pool-size: 8
    keep-alive-seconds: 30
    queue-size: 200
    thread-name-prefix: QuartzThread

  elasticsearch:
    host: ${ES_HOST}
    port: ${ES_PORT}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    product-index-name: product-es-index-v1

logging:
  level:
    com.mall.business.mapper: debug
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  qiniu:
    access-key: ${QINIU_ACCESSKEY}
    secret-key: ${QINIU_SECRETKEY}
    file-bucket-name: ${QINIU_FILE_BUCKET_NAME}
    file-domain: ${QINIU_FILE_DOMAIN}