server:
  port: 8011

spring:
  profiles:
    active: dev
  application:
    name: mall-web-application

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/my_mall?&characterEncoding=utf8"

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

  cache:
    cache-names: dict_data
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=60s

  mail:
    protocol: ${MAIL_PROTOCOL:smtp}
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    default-encoding: ${MAIL_DEFAULT_ENCODING:UTF-8}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    # properties可配置属性参考:
    # https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn

my-mall:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400}   # 1 天(秒)
  captcha:
    expiration: ${CAPTCHA_EXPIRATION:120}
  password:
    private-key-path: ./pri.key

ip2region:
  db-path: ${IP2REGION_DB_PATH:classpath:ip2region/ip2region.xdb}

ip-geolocation:
  api: ${IP_GEO_API:http://ip-api.com/json/}
  city-field-name: ${IP_GEO_CITY_FIELD:city}
  country-field-name: ${IP_GEO_COUNTRY_FIELD:country}
  province-field-name: ${IP_GEO_PROVINCE_FIELD:province}
  params:
    lang: ${IP_GEO_LANG:zh-CN}
